### ISSUE TITLE
needs some basic usage docs ;)

### ISSUE THREAD

**Issue by kristianmandrup** [feathersjs-ecosystem/feathers-stripe#1]
From `https://github.com/feathersjs/feathers-stripe/blob/master/src/index.js` I gather you could do:

`import { card as Card, charge as Charge, customer as Customer, plan as Plan} from 'feathers-stripe'`

In order to get started... each service takes an `apiKey` options:

`const stripeCard = new Card({apiKey: 'xxxxxxx');`

To use, see Stripe API. Each class is just a CRUD entity with basic stripe attributes.

**Comment by corymsmith** [comment]
I think this is still in progress, right @ekryski? If so, we may want to add that to the Readme.

**Comment by ekryski** [comment]
Definitely still in progress. I'm not even sure if it works yet.

**Comment by ekryski** [comment]
I've update the docs a bit. I think we can close this now.
