### ISSUE TITLE
Are Prices service instead of Plan available with this package ?

### ISSUE THREAD

**Issue by Datebayo350** [feathersjs-ecosystem/feathers-stripe#104]
Hello, i would like to know if we have any posibilities to get the Price service instead of Plan, is it available or in building ...? 
Thanks for your replyes

**Comment by DaddyWarbucks** [comment]
@Datebayo350 I know this is super late. But I think I can add this for you.

**Comment by DaddyWarbucks** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-stripe/pull/108
