### ISSUE TITLE
Add subscription service

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs-ecosystem/feathers-stripe#2]
Just after a subscriptions service to subscribe a given customer to a plan. I'm working on a PR for it - but the problem with the subscription is that it needs a customer ID involved too, it's not just the ID of a subscription needed. My initial thoughts is just to look for `user` on `params` which will contain the ID, though I'm not sure if this is somewhat opinionated - thoughts? Or have there been any other ideas on how to make a subscriptions service?

**Comment by ekryski** [comment]
@bedeoverend definitely something we want to add. I think what you described is the way to probably do it. What we have done in the past is use a `before` hook on the subscription service to set up the data that you require to create a subscription object with Stripe. This includes calling other services or looking up the current user to get the `cusomer_id`.

**Comment by bedeoverend** [comment]
@ekryski excellent - yeah that's exactly what I've done, I've made a stripe subscriptions service that has a before hook to attached the `customer` to the incoming `data` object. I'd like to make a PR to add the service plugin, do I just need to follow the same format you've used for the other services?

**Comment by ekryski** [comment]
@bedeoverend whoa! I missed this. Sorry. If you're still up for a PR I'd love to see it. Haven't had the need to implement subscriptions (yet). Ideally if you can follow a similar format that would be cool. Either way we can figure it out/comment on the PR
