### ISSUE TITLE
Can this be used?

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-stripe#26]
The warning about use in production has been there for some time, just wondering if it's safe to use or if I should leave it for now.

**Comment by daffl** [comment]
Install it and see if it does what you need it to. The note also says that pull request are welcome if you find functionality/documentation missing or you think the warning can be removed.

**Comment by dottodot** [comment]
It's the "is not ready for production" that's a bit off putting, suggests it shouldn't be used and if it just missing some features I'd probably reword it as it advises what's available further down.

**Comment by daffl** [comment]
This adapter has been used in apps we built but I let you be the judge of it and welcome a PR if things suit your needs 😄
