### ISSUE TITLE
Add support for sources

### ISSUE THREAD

**Issue by fmoessle** [feathersjs-ecosystem/feathers-stripe#38]
I did not found support for sources in the readme and the code.

Will you provide support for sources in the near future?

[Stripe Source Docs](https://stripe.com/docs/api#create_source)

**Comment by daffl** [comment]
New services all look very similar (e.g. to https://github.com/feathersjs-ecosystem/feathers-stripe/blob/master/lib/services/charge.js) so it should be fairly straightforward to add if you want to have a stab at it.

**Comment by daffl** [comment]
Closed via #52
