### ISSUE TITLE
Can't pass params to .remove calls

### ISSUE THREAD

**Issue by wdmtech** [feathersjs-ecosystem/feathers-stripe#40]
Hey @daffl 

Only one parameter is accepted in `.remove(id)` calls.
This of course means I have to use the services' Stripe object directly (which is fine for now!)

For instance, I want to write the following:

```js
subscriptionsService.remove(subscription.id, { at_period_end: true })
```

But instead, I have to write:

```js
subscriptionsService.stripe.subscriptions.del(subscription.id, { at_period_end: true })
```

Example of a `.remove` call that only accepts an `id` with no `params`

https://github.com/feathersjs-ecosystem/feathers-stripe/blob/master/lib/services/subscription.js#L28

I'm happy to send a PR if you think this should be added.

Cheers 😀

**Comment by daffl** [comment]
Yes, it should use `params.stripe` and call

```js
return this.stripe.subscriptions.del(id, params.stripe).catch(errorHandler);
```

In https://github.com/feathersjs-ecosystem/feathers-stripe/blob/master/lib/services/subscription.js#L28

**Comment by ericuldall** [comment]
Hey guys,

I  had an issue implementing the DELETE method on the subscription service. params.stripe doesn't exist. Is this something that should be added when making the api call? Perhaps it makes more sense to do something like the following as a fallback:
```
return this.stripe.subscriptions.del(id, params.stripe || {}).catch(errorHandler);
```

For now I've just added a before hook that assigns params.stripe to an empty object, but it took some tinkering to realize the problem.

Thoughts?
