### ISSUE TITLE
Use the Charge service remove method to refund a charge

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-stripe#62]
I noticed that there is a kind of “helper” method on the `Transfer` service that creates a `TransferReversal` when calling the `remove` method on that service, and that has been nice to use. When either a charge or a transfer are refunded/reversed, that refund/reversal info is available on the charge/transfer itself without having to explicitly lookup the actual refund or reversal. That makes it quite nice to deal with a charge/refund and a transfer/reversal within the same service.

**Comment by daffl** [comment]
Closed via #63
