### ISSUE TITLE
Allow query to be passed to `Balance` service

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-stripe#64]
The `Balance` service's methods do not pass any params to the underlying stripe methods, as seen here: https://github.com/feathersjs-ecosystem/feathers-stripe/blob/a388b8e05248d539507a18ee55de2f8eaed277cb/lib/services/balance.js#L7

But, the `stripe.balance` method does actually accept query parameters, specifically `stripe_account`. When fetching a balance without providing a `stripe_account`, the balance of the account holding the keys is returned. But, when using Stripe Connect, we can manage other accounts and need to be able to fetch their balance.

You can see an example of this working here: https://github.com/stripe/stripe-connect-rocketrides/blob/897716cae8130f76254a71f6d1258c6b6f85dbc9/server/routes/pilots/pilots.js#L33

I propose that the `Balance` service's `get` and `find` methods pass `params.query` to the underlying stripe method.

**Comment by daffl** [comment]
Closed via #64
