### ISSUE TITLE
this.stripe.customers.updateCard is not a function

### ISSUE THREAD

**Issue by jordan-mcrae** [feathersjs-ecosystem/feathers-stripe#68]
We recently started running into the issue where certain methods on the Card service don't seem to exist anymore. I'm not sure if this is an issue with `feathers-stripe` or whether something has changed on the `Stripe` side.

#### Error:
```
error: TypeError: this.stripe.customers.updateCard is not a function
at Service.update (myProject/node_modules/feathers-stripe/lib/services/card.js:40:34)
at Service.patch (myProject/node_modules/feathers-stripe/lib/services/card.js:33:17)
```

#### Steps to Reproduce:

```
const StripeCardService = new Card({ secretKey });

await StripeCardService.patch(preExistingStripeCard.id, {
  address_city    : data.address_city,
  address_country : data.address_country,
  address_line1   : data.address_line1,
  address_state   : data.address_state,
  address_zip     : data.address_zip,
  email           : data.email,
  name            : data.name,
}, {customer: currentUser.id});
```

#### Versions:  
`feathers-stripe : "0.8.0"`  
`stripe                 : "^7.5.2"`  
`Node                  : "10.15.0"`

[This is the line of code in question](https://github.com/feathersjs-ecosystem/feathers-stripe/blob/ba92d1d5cb1bfc72aa8c1aee2e550ee02f16b2b5/lib/services/card.js#L40).

Any help would be greatly appreciated. Thanks!

**Comment by daffl** [comment]
This is because the Stripe library dependency has been updated to the latest version. See the [migration guide](https://github.com/stripe/stripe-node/wiki/Migration-guide-for-v7) for more information.
