### ISSUE TITLE
Add support for Stripe webhooks

### ISSUE THREAD

**Issue by ekryski** [feathersjs-ecosystem/feathers-stripe#8]

**Comment by sdbondi** [comment]
Hey @ekryski, I created this feathers service library for stripe webhooks. https://github.com/fixate/feathers-stripe-webhooks - maybe it can help

**Comment by ekryski** [comment]
@sdbondi that looks great! Any chance you want to PR that into this module to consolidate them all?

**Comment by sdbondi** [comment]
@ekryski sure, makes sense to me! Should be able to get on that in a week or two :+1:

**Comment by subodhpareek18** [comment]
Hi, @sdbondi any possibilities of a PR anytime soon?

**Comment by sdbondi** [comment]
Hi @zusamann, shouldn't be a huge job, but still super busy. Can't make any promises, but I'll keep it on my radar if I find some spare time - I'd like to get this done. In the mean time, [the existing module](https://github.com/fixate/feathers-stripe-webhooks) is running well in production so you can use it and switch it out later, which is likely to be straightforward without breaking API changes.

**Comment by subodhpareek18** [comment]
Ok thanks!
