### ISSUE TITLE
Typical usage scenario

### ISSUE THREAD

**Issue by emmanuelgeoffray** [feathersjs-ecosystem/feathers-stripe#94]
Hello,

I am not sure how to use theses feathersjs services.
I am fluent in feathersjs, but new to stripe, which doesn't help understanding how feathers-stripe removes the need of rewriting code.

From what I understand the strip services are made to be used internally, not from routes. How is it easier to use a service instead of calling directly the node-stripe module? I guess there is a reason, but can't see it from my level.

I tried to implement the process of an user subscribing for a monthly plan:  https://stripe.com/docs/payments/checkout/subscriptions/starting

1. Checkout: I did not found the Checkout service in feathers-stripe, so I created a custom service, with node-stripe used inside the class, to create the Session.
2. After the payment: I wrote a custom after hook for user, that uses the Customer service to get the subscription status.

Is my implementation of the scenario correct? Or am I missing a feature of feathers-stripe?

Thank you!
Emmanuel

**Comment by emmanuelgeoffray** [comment]
Hey @marshallswain 
Can we have a quick chat so I can help on this?

**Comment by marshallswain** [comment]
I admit that I don't have a lot of experience with feathers-stripe.  As far as I'm aware, it's a thin wrapper around the Stripe API that makes it more feathers-like.  You make a service for each type of Stripe resource you need, which you would probably want to do, anyway.  A conversation with me about this topic would not be productive, at all.  ;)

**Comment by amoghpalnitkar** [comment]
As @marshallswain correctly pointed out, feathers-stripe is a wrapper around the Stripe API, allowing you to call external Stripe APIs the feathers way.
One possible example that I can think of the top of my head is, say, you want to send an email to your customer after every Stripe Charge, which can be done using after hooks on the stripe-charges service. 
Of course you can do this using node-stripe library as well, but I hope you get the point :)
